name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: setup@v1
      - run: pnpm lint
  prettier-check:
    runs-on: ubuntu-latest
    steps:
      - uses: setup@v1
      - run: pnpm prettier-check
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: setup@v1
      - run: pnpm build
