name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    steps:
      - uses: ./actions/setup
      - run: pnpm lint
  prettier-check:
    steps:
      - uses: ./actions/setup
      - run: pnpm prettier-check
  build:
    steps:
      - uses: ./actions/setup
      - run: pnpm build
